on: [push, pull_request]
name: Lint
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: PHP-CS-Fixer
      working-directory: ./App
      with:
        php-version: 8.2
    - run: composer install
    - run: php vendor/bin/php-cs-fixer fix --dry-run
