on: [push, pull_request]
name: Lint
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    container:
      image: php:8.3-apache
    steps:
    - uses: actions/checkout@v5

    - name: Composer dependencies
      working-directory: ./App
      run: composer install

    - name: PHP CS Fix
      working-directory: ./App
      run: php vendor/bin/php-cs-fixer fix --dry-run
