on: [push, pull_request]
name: Lint
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    container:
      image: php:8.3-apache
    steps:
    - uses: actions/checkout@v5

    - name: Install git
      run: |
        apt-get update
        apt-get install git

    - name: Install composer
      working-directory: ./App
      run: |
        EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

        if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
        then
          >&2 echo 'ERROR: Invalid installer checksum'
          rm composer-setup.php
          exit 1
        fi

        php composer-setup.php --quiet
        RESULT=$?
        rm composer-setup.php
        exit $RESULT

    - name: Composer dependencies
      working-directory: ./App
      run: |
        ./composer.phar install

    - name: PHP CS Fix
      working-directory: ./App
      run: php vendor/bin/php-cs-fixer fix --dry-run
