on: [push, pull_request]
name: Lint
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    container:
      image: php:8.3-apache
    steps:
    - uses: actions/checkout@v5

    - name: Install composer
      run: wget https://raw.githubusercontent.com/composer/getcomposer.org/f3108f64b4e1c1ce6eb462b159956461592b3e3e/web/installer -O - -q | php -- --quiet

    - name: Composer dependencies
      working-directory: ./App
      run: composer install

    - name: PHP CS Fix
      working-directory: ./App
      run: php vendor/bin/php-cs-fixer fix --dry-run
